package com.example.exm;

public enum RM { // REQUEST METHOD
    DUPLICATE_KEY,
    DUPLICATE_ID,
    ADD_USER,
    CHECK_PASS,
    GET_TWEETS,
    ADD_TWEET,
    LAST_SEEN_TIME,
    GET_USER,
    FOLLOW_REQUEST,
    LIKE_TWEET,
    DISCOVER_USERS,
    END_PROCESS
}
